//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFIGestionProveedores04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion_Proveedor
    {
        public int idCalificacion_Proveedor { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idCalificacion { get; set; }
    
        public virtual Calificacion Calificacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
