//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFIGestionProveedores04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int idEquipo { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> Fecha_Adqu { get; set; }
        public Nullable<System.DateTime> Fecha_FinGarantia { get; set; }
        public Nullable<int> idProveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
