//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFIGestionProveedores04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public int idTecnico { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Direcccion { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
